version: 0.2


phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm install -g typescript
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm start
artifacts:
  files:
    - '**/*'
  name: testbuild-$(date +%Y-%m-%d)